services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: dotnet-backend

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: "Host=YOUR_RDS_ENDPOINT;Port=5432;Database=YOUR_DATABASE;Username=YOUR_USERNAME;Password=YOUR_PASSWORD"

    ports:
      - "8080:8080"

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: react-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped